def get_main_prompt(question: str, chunk: str) -> str:
    """
    Description:
    Generates a prompt for the Gemini API based on the user's question and a specific chunk of text extracted from a PDF. 
    The prompt instructs the model to provide an answer strictly from the given content without personal knowledge.

    Parameters:
    question (str): The user's question.
    chunk (str): A chunk of text extracted from the PDF file.

    Returns:
    str: A formatted prompt string for the Gemini API.
    """
    prompt = f"""
    You are provided with a question from user and information from PDF file.
    Your task is to answer user's question only relying on information from PDF file.
    Do not use any of your personal knowledge. 
    Do not repeat any statements or content you've already provided in the answer. Keep the response concise and to the point.
    If there is no information about user's question in PDF file return "PDF file does not contain any information about your question"

    QUESTION:
    {question}

    PDF Content:
    {chunk}
    """
    return prompt


def get_additional_prompt(question: str, chunk: str, prev_response: str) -> str:
    """
    Description:
    Creates a prompt for the Gemini API that incorporates both the user's question and a previous response. 
    This prompt aims to enrich the previous answer with new information from the specified PDF chunk while ensuring no repeated content.

    Parameters:
    question (str): The user's question.
    chunk (str): A chunk of text extracted from the PDF file.
    prev_response (str): The previous response generated by the API.
    
    Returns:
    str: A formatted prompt string for the Gemini API that includes the previous answer.
    """
    prompt = f"""
    You are provided with a question from user and information from PDF file.
    Your task is to answer user's question only relying on information from PDF file.
    Do not use any of your personal knowledge. 
    If there is no information about user's question in PDF file return "PDF file does not contain any information about your question"
    Do not repeat any statements or content you've already provided in the answer. Keep the response concise and to the point.
    At this time we have answer from previous iterations. Enrich this answer by new information from file.
    If previous answer contains correct answer return previous answer.
    QUESTION:
    {question}

    Previous answer:
    {prev_response}

    PDF Content:
    {chunk}
    """
    return prompt